# Generated by Django 5.0.4 on 2024-04-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_rename_url_video_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.FileField(upload_to='media/videos'),
        ),
    ]
