# Generated by Django 5.0.4 on 2024-04-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_efficiency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlog',
            name='material_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
