# Generated by Django 5.0.4 on 2024-04-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_efficiency', '0002_productionlog_material_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlog',
            name='available_time',
            field=models.CharField(choices=[('shift 1', 'shift 1'), ('shift 2', 'shift 2'), ('shift 3', 'shift 3')], default='shift 1', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionlog',
            name='total_product',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
