# Generated by Django 5.0.4 on 2024-04-21 10:07

import machine_efficiency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_efficiency', '0003_productionlog_available_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlog',
            name='ideal_cycle_time',
            field=models.DurationField(default=machine_efficiency.models.default_duration),
        ),
    ]
