# Generated by Django 5.0.4 on 2024-04-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_efficiency', '0006_alter_productionlog_actual_output_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionlog',
            name='unique_id',
        ),
    ]
