# Generated by Django 5.0.4 on 2024-04-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_efficiency', '0007_remove_productionlog_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionlog',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
