# Generated by Django 5.0.4 on 2024-04-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_efficiency', '0008_alter_productionlog_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionlog',
            name='cycle_no',
        ),
    ]
