# Generated by Django 5.0.4 on 2024-04-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_efficiency', '0009_remove_productionlog_cycle_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlog',
            name='cycle_no',
            field=models.CharField(default='GN-0001', max_length=200),
            preserve_default=False,
        ),
    ]
